
function FindProxyForURL(url, host) {
	
	if(isInNet(dnsResolve(host), "66.55.146.154", "255.255.255.255")) return "DIRECT";
	if(isInNet(dnsResolve(host), "23.29.130.40", "255.255.255.255")) return "DIRECT";
	if(isInNet(dnsResolve(host), "107.191.32.242", "255.255.255.255")) return "DIRECT";
	if(isInNet(dnsResolve(host), "208.100.44.165", "255.255.255.255")) return "DIRECT";
	if(dnsDomainIs(host, "geder.org")) return "DIRECT";
	if(isInNet(dnsResolve(host), "127.0.0.1", "255.0.0.0")) return "DIRECT";
	if(isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0")) return "DIRECT";
	if(isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0")) return "DIRECT";
	if(isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0")) return "DIRECT";
	if(dnsDomainIs(host, "ny.gov")) return "DIRECT";
	if(dnsDomainIs(host, "sba.gov")) return "DIRECT";
	if(dnsDomainIs(host, "cbsa-asfc.cloud-nuage.canada.ca")) return "DIRECT";
	if(dnsDomainIs(host, ".icloud.com")) return "DIRECT";
	if(dnsDomainIs(host, "iosapps.itunes.apple.com")) return "DIRECT";
	if(dnsDomainIs(host, ".icloud-content.com")) return "DIRECT";
	if(dnsDomainIs(host, ".blobstore.apple.com")) return "DIRECT";
	if(shExpMatch(url, "*gcs-*.content-storage-upload.googleapis.com*")) return "DIRECT";
	if(shExpMatch(url, "*gcs-*.content-storage-download.googleapis.com*")) return "DIRECT";
	if(dnsDomainIs(host, "us-ore-00001.s3.dualstack.us-west-2.amazonaws.com")) return "DIRECT";
	if(dnsDomainIs(host, "us-std-00001.s3.dualstack.us-east-1.amazonaws.com")) return "DIRECT";
	if(dnsDomainIs(host, "eu-irl-00001.s3.dualstack.eu-west-1.amazonaws.com")) return "DIRECT";
	if(dnsDomainIs(host, "cloudfront.yiddish24.com")) return "DIRECT";
	if(dnsDomainIs(host, "photos.googleapis.com")) return "DIRECT";
	if(dnsDomainIs(host, "swcdn.apple.com")) return "DIRECT";
	if(dnsDomainIs(host, ".myvzw.com")) return "DIRECT";
	if(dnsDomainIs(host, ".vtext.com")) return "DIRECT";
	if(dnsDomainIs(host, "myvzw.com")) return "DIRECT";
	if(dnsDomainIs(host, "vtext.com")) return "DIRECT";
	if(dnsDomainIs(host, "vzwpix.com")) return "DIRECT";
	if(dnsDomainIs(host, ".vzw.com")) return "DIRECT";
	if(dnsDomainIs(host, "vzw.com")) return "DIRECT";
	if(shExpMatch(url, "*vzwpix.com*")) return "DIRECT";
	if(shExpMatch(url, "*myvzw.com*")) return "DIRECT";
	if(shExpMatch(url, "*vtext.com*")) return "DIRECT";
	if(shExpMatch(url, "*vzw.com*")) return "DIRECT";
	if(shExpMatch(url, "*vzmessages.com*")) return "DIRECT";
	if(dnsDomainIs(host, "sprintpcs.com")) return "DIRECT";
	if(dnsDomainIs(host, "mms.mvno.com")) return "DIRECT";
	if(dnsDomainIs(host, "mms.sprint.com")) return "DIRECT";
	if(dnsDomainIs(host, "t-mobile.com")) return "DIRECT";
	if(dnsDomainIs(host,"s.whatsapp.net")) return "DIRECT";
	if(shExpMatch(url, "*whatsapp.com*")) return "DIRECT";
	if(shExpMatch(url, "*whatsapp.net*")) return "DIRECT";
	if(shExpMatch(url, "*/u/*A*/A*")) return "DIRECT";
	if(shExpMatch(url, "*/d/*/A*aac*")) return "DIRECT";
	if(shExpMatch(url, "*/d/*/A*amr*")) return "DIRECT";
	if(shExpMatch(url, "*edge.icloud-content.com*")) return "DIRECT";
	if(shExpMatch(url, "*cvws.icloud-content.com/*com.apple.photos.cloud*")) return "DIRECT";
	if(shExpMatch(url, "*cdn.icloud-content.com/*ckc=Ccom.apple.news.public*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*setup.icloud.com/*com.apple.news.publi*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*radio.itunes.apple.com*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*radio-services.itunes.apple.com*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*se2.itunes.apple.com*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*cdn.icloud-content.com/*ckc=Ccom.apple.news.public*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*setup.icloud.com/*com.apple.news.publi*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*smoot.apple.com*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*tenor.co*")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*giphy.com*")) return "PROXY 0.0.0.0:1234";
	if(dnsDomainIs(host, "www.appleiphonecell.com")) return "DIRECT";
	if(dnsDomainIs(host, "captive.apple.com")) return "DIRECT";
	if(dnsDomainIs(host, "www.thinkdifferent.us")) return "DIRECT";
	if(dnsDomainIs(host, "www.airport.us")) return "DIRECT";
	if(dnsDomainIs(host, "www.itools.info")) return "DIRECT";
	if(dnsDomainIs(host, "www.ibook.info")) return "DIRECT";
	if(shExpMatch(url, "*guzzoni.apple.com*")) return "DIRECT";
	if(shExpMatch(url, "*identity.apple.com*")) return "DIRECT";
	if(shExpMatch(url, "*configuration.apple.com*")) return "DIRECT";
	if(shExpMatch(url, "*appleid.apple.com*")) return "DIRECT";
	if(shExpMatch(url, "*icloud.com*")) return "DIRECT";
	if(dnsDomainIs(host, "ads-resources.waze.com")) return "PROXY 0.0.0.0:1234";
	if(dnsDomainIs(host, "advil.waze.com")) return "PROXY 0.0.0.0:1234";
	if(dnsDomainIs(host, "ads-resources-legacy.waze.com")) return "PROXY 0.0.0.0:1234";
	if(dnsDomainIs(host, "row-advil.waze.com")) return "PROXY 0.0.0.0:1234";
	if(dnsDomainIs(host, "waze.com")) return "DIRECT";
	if(dnsDomainIs(host, "waze.co.il")) return "DIRECT";
	if(dnsDomainIs(host, "gogoinflight.com")) return "DIRECT";
	if(dnsDomainIs(host, "gogo.com")) return "DIRECT";
	if(dnsDomainIs(host, "boingohotspot.net")) return "DIRECT";
	if(dnsDomainIs(host, "selectnetworx.com")) return "DIRECT";
	if(dnsDomainIs(host, "msftconnecttest.com")) return "DIRECT";
	if(dnsDomainIs(host, "air2data.com")) return "DIRECT";
	if(dnsDomainIs(host, "spectrum.com")) return "DIRECT";
	if(dnsDomainIs(host, "wifipass.org")) return "DIRECT";
	if(dnsDomainIs(host, "key.com")) return "DIRECT";
	if(dnsDomainIs(host, "telekom.com")) return "DIRECT";
	if(dnsDomainIs(host, "socialwifi.com")) return "DIRECT";
	if(dnsDomainIs(host, "elal.co.il")) return "DIRECT";
	if(dnsDomainIs(host, "elal.com")) return "DIRECT";
	if(dnsDomainIs(host, "elal-matmid.com")) return "DIRECT";
	if(dnsDomainIs(host, "hotspot.t-mobile.com")) return "DIRECT";
	if(dnsDomainIs(host, "flynet.com")) return "DIRECT";
	if(dnsDomainIs(host, "lufthansa-flynet.com")) return "DIRECT";
	if(dnsDomainIs(host, "paypal.com")) return "DIRECT";
	if(dnsDomainIs(host, "computop-paygate.com")) return "DIRECT";
	if(dnsDomainIs(host, "services.inflightpanasonic.aero")) return "DIRECT";
	if(dnsDomainIs(host, "inflightpanasonic.aero")) return "DIRECT";
	if(dnsDomainIs(host, "delta.com")) return "DIRECT";
	if(dnsDomainIs(host, "inflight-wifi.com")) return "DIRECT";
	if(dnsDomainIs(host, "finnair.com")) return "DIRECT";
	if(dnsDomainIs(host, "virginatlantic.com")) return "DIRECT";
	if(dnsDomainIs(host, "spirit.com")) return "DIRECT";
	if(dnsDomainIs(host, "itau.com.ar")) return "DIRECT";
	if(dnsDomainIs(host, "itau.com.br")) return "DIRECT";
	if(dnsDomainIs(host, "tradestation.com")) return "DIRECT";
	if(dnsDomainIs(host, "viasat.com")) return "DIRECT";
	if(dnsDomainIs(host, "aainflight.com")) return "DIRECT";
	if(dnsDomainIs(host, "wifi.united.com")) return "DIRECT";
	if(dnsDomainIs(host, "gogoair.com")) return "DIRECT";
	if(dnsDomainIs(host, "wifionboard.com")) return "DIRECT";
	if(dnsDomainIs(host, "swisscom.ch")) return "DIRECT";
	if(dnsDomainIs(host, "aa.com")) return "DIRECT";
	if(dnsDomainIs(host, "connectivitycheck.gstatic.com")) return "DIRECT";
	if(dnsDomainIs(host, "guestwifi-us.skyfii.com")) return "DIRECT";
	if(dnsDomainIs(host, "skyfii.io")) return "DIRECT";
	if(dnsDomainIs(host, "r4---sn-ntqe6n7k.gvt1.com")) return "DIRECT";
	if(dnsDomainIs(host, "offline-maps.gvt1.com")) return "DIRECT";
	if(dnsDomainIs(host, "mcafee.com")) return "DIRECT";
	if(dnsDomainIs(host, "mcafeemobilesecurity.com")) return "DIRECT";
	if(dnsDomainIs(host, "xcap.private.att.net")) return "DIRECT";
	if(dnsDomainIs(host, "turktelekomwififly.com")) return "DIRECT";
	if(dnsDomainIs(host, "tkwifi.net")) return "DIRECT";
	if(dnsDomainIs(host, "snap.safetyaccess.com")) return "DIRECT";
	if(dnsDomainIs(host, "tracfone.com")) return "DIRECT";
	if(dnsDomainIs(host, "tmocce.com")) return "DIRECT";
	if(dnsDomainIs(host, "fingercheck.com")) return "DIRECT";
	if(shExpMatch(url, "*gogoair.com*")) return "DIRECT";
	if(shExpMatch(url, "*united.com/*/travel/inflight/wifi*")) return "DIRECT";
	if(shExpMatch(url, "*gogoinflight*")) return "DIRECT";
	if(shExpMatch(url, "*unitedwifi.com*")) return "DIRECT";
	if(shExpMatch(url, "*flyfi.*")) return "DIRECT";
	if(shExpMatch(url, "*elal.co.il*")) return "DIRECT";
	if(shExpMatch(url, "*elal.co,*")) return "DIRECT";
	if(shExpMatch(url, "*flyfi.com*")) return "DIRECT";
	if(shExpMatch(url, "*wifi*.optimum.net*")) return "DIRECT";
	if(dnsDomainIs(host, "unitedwifi.com")) return "DIRECT";
	if(dnsDomainIs(host, "www.flyfi.com")) return "DIRECT";
	if(dnsDomainIs(host, "flyfi.com")) return "DIRECT";
	if(dnsDomainIs(host, "www.united.com")) return "DIRECT";
	if(dnsDomainIs(host, "gocloud1.com")) return "DIRECT";
	if(shExpMatch(url, "*swissconnectforguests.com*")) return "DIRECT";
	if(shExpMatch(url, "*deltawifi.com*")) return "DIRECT";
	if(shExpMatch(url, "*elal.viasat.com*")) return "DIRECT";
	if(shExpMatch(url, "*wifi.elal.com*")) return "DIRECT";
	if(shExpMatch(url, "*scilearn.com*")) return "DIRECT";
	if(dnsDomainIs(host, "scilearn.com")) return "DIRECT";
	if(dnsDomainIs(host, "gmail.com")) return "DIRECT";
	if(dnsDomainIs(host, "emailsrvr.com")) return "DIRECT";
	if(dnsDomainIs(host, "mail.yahoo.com")) return "DIRECT";
	if(dnsDomainIs(host, "thejnet.com")) return "DIRECT";
	if(dnsDomainIs(host, "swdhost.com")) return "DIRECT";
	if(dnsDomainIs(host, "secureserver.net")) return "DIRECT";
	if(dnsDomainIs(host, "mail.me.com")) return "DIRECT";
	if(shExpMatch(url, "*outlook.office365.com*")) return "DIRECT";
	if(shExpMatch(url, "*mail*Microsoft-Server-ActiveSync?*")) return "DIRECT";
	if(shExpMatch(url, "*tmocce.com*")) return "DIRECT";
	if(shExpMatch(url, "*acris.nyc.gov*")) return "DIRECT";
	if(shExpMatch(url, "*resgister-app.amazon.com*")) return "DIRECT";
	if(shExpMatch(url, "*.capitalone.com*")) return "DIRECT";
	if(shExpMatch(url, "*torahanytime.com*")) return "DIRECT";
	if(shExpMatch(url, "*oa.ft.newyorklife.com*")) return "DIRECT";
	if(shExpMatch(url, "*.manage.microsoft.com*")) return "DIRECT";
	if(shExpMatch(url, "*.enterpriseregistration.windows.net*")) return "DIRECT";
	if(shExpMatch(url, "*.awsegexchp.glic.com*")) return "DIRECT";
	if(dnsDomainIs(host, "bugsense.com")) return "DIRECT";
	if(dnsDomainIs(host, "samsungipolis.com")) return "DIRECT";
	if(dnsDomainIs(host, "intelligenthome.timewarnercable.com")) return "DIRECT";
	if(dnsDomainIs(host, "drive.google.com")) return "DIRECT";
	if(dnsDomainIs(host, "docs.google.com")) return "DIRECT";
	if(isInNet(dnsResolve(host), "72.249.68.229", "255.255.255.255")) return "DIRECT";
	if(dnsDomainIs(host, "chsdw.com")) return "DIRECT";
	if(dnsDomainIs(host, "fabuwood.com")) return "DIRECT";
	if(dnsDomainIs(host, "koshernear.me")) return "DIRECT";
	if(dnsDomainIs(host, "music.yiddish24.com")) return "DIRECT";
	if(isInNet(dnsResolve(host), "149.154.160.0", "255.255.240.0")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(host, "t.co")) return "PROXY 0.0.0.0:1234";
	if(shExpMatch(url, "*twimg.com*")) return "PROXY 0.0.0.0:1234";
	
	return "PROXY vpn-us-nyc1.netfree.link:143";
}
